server:
  port: 6062

spring:
  application:
    name: oauth-service

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    listener:
      simple:
        acknowledge-mode: auto
        retry:
          enabled: true
          max-retries: 5

jwt:
  expiration-time: 36000000
  refresh-expiration-time: 86400000
  secret: ${JWT_SECRET:flpZVEZrUG1ORD01Y2MxInkyP2oiQFFqeTN0TXk4NTk=}

logging:
  level:
    org:
      springframework:
        security: info
        web: info
    root: info

